config/routes.rb
Rails.application.routes.draw do

  root 'tasks#index', as: 'tasks_index'

  namespace :admin do
    root 'base#index'
    resources :users
  end

  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    get 'logout' => :destroy
  end

  resources :users, only: [:show, :new, :edit, :create, :update, :destroy]
  resources :tasks

  controller :dashboard do
    get 'dashboard' => :show
    get 'dashboard/edit' => :edit
    patch 'dashboard' => :update
  end

end

app/models/task.rb
class Task < ApplicationRecord
  validates :title, :description, :priority, :status, presence: true
  belongs_to :user

  STATUS_TODO = 0
  STATUS_DOING = 1
  STATUS_DONE = 2

  enum priority: {
    "Critical" => 0,
    "Important" => 1,
    "Normal" => 2,
    "Low" => 3
  }

  enum status: {
    "To do" => STATUS_TODO,
    "Doing it..." => STATUS_DOING,
    "Done!" => STATUS_DONE
  }


  # Scope to show the tasks filtered by their status.
  scope :todo, -> { where(status: STATUS_TODO).order(:due_date) }
  scope :doing, -> { where(status: STATUS_DOING).order(:due_date) }
  scope :done, -> { where(status: STATUS_DONE).order(:due_date) }

  # Scope to show the tasks with the status todo and Doing
  scope :todo_doing, -> { where(status: [STATUS_TODO, STATUS_DOING])}

  # Scope to show overdue tasks with the status "To do" or "Doing it..."
  scope :overdue, -> { todo_doing.where("due_date <= ?", Date.today ).order(:due_date) }

  # Scope to show upcoming tasks with the status "To do" or "Doing it..."
  scope :upcoming, -> { todo_doing.where(due_date: (Date.current)..Date.current+7).order(:due_date).limit(6) }

  # Method to check if task is overdue
  def overdue?
    if self.try(:due_date)
      self.due_date <= Date.today
    end
  end


end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]
  skip_before_action :authorize, only: [:index]

  # GET /tasks
  # GET /tasks.json
  def index
    @tasks = Task.all
    if current_user
      @todo = current_user.tasks.todo
      @doing = current_user.tasks.doing
      @done = current_user.tasks.done
    else
      @todo =  Task.todo
      @doing = Task.doing
      @done = Task.done
    end
  end

  # GET /tasks/1
  # GET /tasks/1.json
  def show
  end

  # GET /tasks/new
  def new
    @task = current_user.tasks.build()
  end

  # GET /tasks/1/edit
  def edit
  end

  # POST /tasks
  # POST /tasks.json
  def create
    @task = current_user.tasks.create(task_params)

    respond_to do |format|
      if @task.save
        format.html { redirect_to @task, notice: 'Task was successfully created.' }
        format.json { render :show, status: :created, location: @task }
      else
        format.html { render :new }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1
  # PATCH/PUT /tasks/1.json
  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to @task, notice: 'Task was successfully updated.' }
        format.json { render :show, status: :ok, location: @task }
      else
        format.html { render :edit }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @task.destroy
    respond_to do |format|
      format.html { redirect_to tasks_url, notice: 'Task was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def task_params
      params.require(:task).permit(:title, :description, :priority, :status, :due_date)
    end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/tasks/_form.html.erb
<%= form_for(task) do |f| %>
  <% if task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
      <% task.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field field--long">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="field field--long">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>

  <div class="field field--short">
    <%= f.label :priority %>
    <%= f.select :priority, Task.priorities.keys %>
  </div>

  <div class="field field--short">
    <%= f.label :status %>
    <%= f.select :status, Task.statuses.keys %>
  </div>

  <div class="field field--short">
    <%= f.label :due_date %>
    <%= f.date_field :due_date %>
  </div>

  <div class="actions">
    <%= f.submit 'Save Task', :class => "button"  %>
  </div>
<% end %>

app/views/tasks/edit.html.erb
<h1>Editing Task</h1>

<%= render 'form', task: @task %>

<%= link_to 'Show', @task %> |
<%= link_to 'Back', tasks_path %>

app/views/tasks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Tasks</h1>

<%= button_to 'New Task', new_task_path, method: :get, class: "button" %>

<div class="row align-justify align-top tasks-overwiev">
  <article class="small-13 medium-13 large-4 column large-expand task-column">
    <h1 class="task-column--title"><%= @tasks.statuses.keys[0] %></h1>
    <% if current_user %>
      <% @todo.each do |task| %>
        <div class="task todo">
          <h1 class="task--title"><%= task.title %></h1>
          <% if task.overdue? %>
            <span class="task__overdue alert badge">Overdue!</span>
          <% end %>
          <p><%= task.description %></p>
          <p><strong>Priority: </strong><%= task.priority %></p>
          <p><strong>Status: </strong><%= task.status %></p>
          <% if task.due_date? %><p><strong>Due Date: </strong><%= task.due_date %></p><% end %>
          <%= button_to 'Edit', edit_task_path(task), method: :get, class: "button secondary" %>
        </div>
      <% end %>
    <% end %>
  </article>

  <article class="small-13 medium-13 large-4 column large-expand task-column">
    <h1 class="task-column--title"><%= @tasks.statuses.keys[1] %></h1>
    <% if current_user %>
      <% @doing.each do |task| %>
        <div class="task doing">
          <h1 class="task--title"><%= task.title %></h1>
          <% if task.overdue? %>
            <span class="task__overdue">Overdue!</span>
          <% end %>
          <p><%= task.description %></p>
          <p><strong>Priority: </strong><%= task.priority %></p>
          <p><strong>Status: </strong><%= task.status %></p>
          <% if task.due_date? %><p><strong>Due Date: </strong><%= task.due_date %></p><% end %>
          <%= button_to 'Edit', edit_task_path(task), method: :get, class: "button secondary" %>
        </div>
      <% end %>
    <% end %>
  </article>

  <article class="small-13 medium-13 large-4 column large-expand task-column">
    <h1 class="task-column--title"><%= @tasks.statuses.keys[2] %></h1>
    <% if current_user %>
      <% @done.each do |task| %>
        <div class="task done">
          <h1 class="task--title"><%= task.title %></h1>
          <p><%= task.description %></p>
          <p><strong>Priority: </strong><%= task.priority %></p>
          <p><strong>Status: </strong><%= task.status %></p>
          <% if task.due_date? %><p><strong>Due Date: </strong><%= task.due_date %></p><% end %>
          <%= button_to 'Edit', edit_task_path(task), method: :get, class: "button secondary" %>
        </div>
      <% end %>
    <% end %>
  </article>

</div>


<br>

app/views/tasks/new.html.erb
<h1>New Task</h1>

<%= render 'form', task: @task %>

<%= link_to 'Back', tasks_index_path %>

<%#= javascript_include_tag "datepicker" %>

app/views/tasks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @task.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @task.description %>
</p>

<p>
  <strong>Priority:</strong>
  <%= @task.priority %>
</p>

<p>
  <strong>Status:</strong>
  <%= @task.status %>
</p>

<p>
  <strong>Due date:</strong>
  <%= @task.due_date %>
</p>

<%= link_to 'Edit', edit_task_path(@task) %> |
<%= link_to 'Back', tasks_path %>