config/routes.rb
Rails.application.routes.draw do

  root 'tasks#index', as: 'tasks_index'

  namespace :admin do
    root 'base#index'
    resources :users
  end

  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    get 'logout' => :destroy
  end

  resources :users, only: [:show, :new, :edit, :create, :update, :destroy]
  resources :tasks

  controller :dashboard do
    get 'dashboard' => :show
    get 'dashboard/edit' => :edit
    patch 'dashboard' => :update
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "DoIt!" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
     <link href="https://fonts.googleapis.com/css?family=News+Cycle:400,700" rel="stylesheet">
    <%= csrf_meta_tags %>
  </head>

  <body>
    <nav class="top-bar">
      <div class="top-bar-title">
        <ul class="menu">
          <li class="menu-text"><%= link_to 'Do It!', tasks_index_path %></li>
        </ul>
      </div>
      <% if current_user.nil? %>
      <div class="top-bar-right">
        <ul class="menu align-right">
          <li><%= link_to "Create Account", new_user_path %></li>
          <li><%= link_to "Login", login_path, :method => :new %></li>
        </ul>
      </div>
      <% else %>
      <div class="top-bar-right">
        <ul class="menu align-right">
          <% if current_user.admin? %>
            <li><%= link_to 'Admin Panel', admin_root_path %>
          <% end %>
          <li><<%= link_to 'Tasks', tasks_index_path %>></li>
          <li><%= link_to 'Dashboard', dashboard_path %></li>
          <li><%= link_to 'My Profile', user_path(current_user) %></li>
          <li><%= link_to "Logout", logout_path %></li>
        </ul>
      </div>
      <% end %>
    </nav>

    <section class="main-section">
      <%= yield %>
    </section>


  </body>
</html>